name: CI

on: push

jobs:
  build:
    name: "✏️ Changelog generation"
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v6
      - name: "✏️ Generate full changelog"
        id: generate-full-changelog
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          headerLabel: "# 📑 Changelog"
          breakingLabel: '### 💥 Breaking'
          enhancementLabel: '### 🚀 Enhancements'
          bugsLabel: '### 🐛 Bug fixes'
          deprecatedLabel: '### ⚠️ Deprecations'
          removedLabel: '### 🔥 Removals'
          securityLabel: '### 🛡️ Security'
          issuesLabel: '### 📁 Other issues'
          prLabel: '### 📁 Other pull requests'
          addSections: '{"documentation":{"prefix":"### 📖 Documentation","labels":["documentation"]},"tests":{"prefix":"### ✅ Testing","labels":["tests"]}}'
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          author: true
          unreleased: true
          compareLink: true
          stripGeneratorNotice: true
          verbose: true
      - name: "🖨️ Print changelog to console"
        run: cat CHANGELOG.md

